// flow-typed signature: 11db4416f8668077f823d46e0c38fe0f
// flow-typed version: <<STUB>>/@immowelt/babel-preset-immowelt-node_v^1.1.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@immowelt/babel-preset-immowelt-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@immowelt/babel-preset-immowelt-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@immowelt/babel-preset-immowelt-node/src/index' {
  declare module.exports: any;
}

declare module '@immowelt/babel-preset-immowelt-node/src/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module '@immowelt/babel-preset-immowelt-node/src/index.js' {
  declare module.exports: $Exports<'@immowelt/babel-preset-immowelt-node/src/index'>;
}
declare module '@immowelt/babel-preset-immowelt-node/src/index.spec.js' {
  declare module.exports: $Exports<'@immowelt/babel-preset-immowelt-node/src/index.spec'>;
}
