// flow-typed signature: ad0e1c81bc0770fe1d2859ec2d461381
// flow-typed version: <<STUB>>/@immowelt/jest-preset-node_v^1.0.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@immowelt/jest-preset-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@immowelt/jest-preset-node' {
  declare module.exports: any;
}
