// flow-typed signature: 4de1a193d627b0db9620ab85b7d25f98
// flow-typed version: <<STUB>>/@immowelt/styleguide-javascript_v^1.0.6/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@immowelt/styleguide-javascript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@immowelt/styleguide-javascript' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@immowelt/styleguide-javascript/src/config' {
  declare module.exports: any;
}

declare module '@immowelt/styleguide-javascript/src/config.spec' {
  declare module.exports: any;
}

declare module '@immowelt/styleguide-javascript/src/lib/createLink' {
  declare module.exports: any;
}

declare module '@immowelt/styleguide-javascript/src/lib/createLink.spec' {
  declare module.exports: any;
}

declare module '@immowelt/styleguide-javascript/src/logger' {
  declare module.exports: any;
}

declare module '@immowelt/styleguide-javascript/src/postinstall' {
  declare module.exports: any;
}

declare module '@immowelt/styleguide-javascript/src/postinstall.spec' {
  declare module.exports: any;
}

declare module '@immowelt/styleguide-javascript/src/preuninstall' {
  declare module.exports: any;
}

declare module '@immowelt/styleguide-javascript/src/preuninstall.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module '@immowelt/styleguide-javascript/src/config.js' {
  declare module.exports: $Exports<'@immowelt/styleguide-javascript/src/config'>;
}
declare module '@immowelt/styleguide-javascript/src/config.spec.js' {
  declare module.exports: $Exports<'@immowelt/styleguide-javascript/src/config.spec'>;
}
declare module '@immowelt/styleguide-javascript/src/lib/createLink.js' {
  declare module.exports: $Exports<'@immowelt/styleguide-javascript/src/lib/createLink'>;
}
declare module '@immowelt/styleguide-javascript/src/lib/createLink.spec.js' {
  declare module.exports: $Exports<'@immowelt/styleguide-javascript/src/lib/createLink.spec'>;
}
declare module '@immowelt/styleguide-javascript/src/logger.js' {
  declare module.exports: $Exports<'@immowelt/styleguide-javascript/src/logger'>;
}
declare module '@immowelt/styleguide-javascript/src/postinstall.js' {
  declare module.exports: $Exports<'@immowelt/styleguide-javascript/src/postinstall'>;
}
declare module '@immowelt/styleguide-javascript/src/postinstall.spec.js' {
  declare module.exports: $Exports<'@immowelt/styleguide-javascript/src/postinstall.spec'>;
}
declare module '@immowelt/styleguide-javascript/src/preuninstall.js' {
  declare module.exports: $Exports<'@immowelt/styleguide-javascript/src/preuninstall'>;
}
declare module '@immowelt/styleguide-javascript/src/preuninstall.spec.js' {
  declare module.exports: $Exports<'@immowelt/styleguide-javascript/src/preuninstall.spec'>;
}
