// flow-typed signature: 681147a65c601637606ca0e8dc8123e7
// flow-typed version: <<STUB>>/eslint-config-xo_v^0.18.2/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-xo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-xo' {
  declare module.exports: any;
}
