// flow-typed signature: 9d1350083f07309d3b352eb0c02c5813
// flow-typed version: <<STUB>>/is-lts_v^1.0.1/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-lts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-lts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'is-lts/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'is-lts/index' {
  declare module.exports: $Exports<'is-lts'>;
}
declare module 'is-lts/index.js' {
  declare module.exports: $Exports<'is-lts'>;
}
declare module 'is-lts/test/test.js' {
  declare module.exports: $Exports<'is-lts/test/test'>;
}
