// flow-typed signature: 79184d6dda01f364feb6d3f2965940be
// flow-typed version: <<STUB>>/log-fancy_v^1.3.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'log-fancy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'log-fancy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'log-fancy/lib/_lib/createColoredLogPrefix' {
  declare module.exports: any;
}

declare module 'log-fancy/lib/_lib/createLogPrefix' {
  declare module.exports: any;
}

declare module 'log-fancy/lib/browser' {
  declare module.exports: any;
}

declare module 'log-fancy/lib/node' {
  declare module.exports: any;
}

declare module 'log-fancy/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'log-fancy/lib/_lib/createColoredLogPrefix.js' {
  declare module.exports: $Exports<'log-fancy/lib/_lib/createColoredLogPrefix'>;
}
declare module 'log-fancy/lib/_lib/createLogPrefix.js' {
  declare module.exports: $Exports<'log-fancy/lib/_lib/createLogPrefix'>;
}
declare module 'log-fancy/lib/browser.js' {
  declare module.exports: $Exports<'log-fancy/lib/browser'>;
}
declare module 'log-fancy/lib/node.js' {
  declare module.exports: $Exports<'log-fancy/lib/node'>;
}
declare module 'log-fancy/lib/types.js' {
  declare module.exports: $Exports<'log-fancy/lib/types'>;
}
