// flow-typed signature: 0a138f3020d773defec8c4abd4a9b4e9
// flow-typed version: <<STUB>>/log-symbols_v^2.0.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'log-symbols'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'log-symbols' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'log-symbols/index' {
  declare module.exports: $Exports<'log-symbols'>;
}
declare module 'log-symbols/index.js' {
  declare module.exports: $Exports<'log-symbols'>;
}
