// flow-typed signature: c6b6b62cf69bb465b392cd16fb06fd04
// flow-typed version: <<STUB>>/node-version_v^1.1.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-version'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-version' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'node-version/index' {
  declare module.exports: $Exports<'node-version'>;
}
declare module 'node-version/index.js' {
  declare module.exports: $Exports<'node-version'>;
}
