// flow-typed signature: ad6f4233655be2c7f1d57cf4ea8d3c05
// flow-typed version: <<STUB>>/semantic-release_v^8.0.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semantic-release'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'semantic-release' {
  declare module.exports: any;
}
