// flow-typed signature: 98979dd672982fd44dd2338b0667cdd4
// flow-typed version: <<STUB>>/sinon_v^3.2.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sinon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sinon' {
  declare module.exports: any;
}
