// flow-typed signature: dfb92ba674b05edcff1db0847734f050
// flow-typed version: <<STUB>>/@immowelt/my-fancy-ui-config_v0.0.0-development/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@immowelt/my-fancy-ui-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@immowelt/my-fancy-ui-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@immowelt/my-fancy-ui-config/src/index' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-config/src/index.production' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-config/src/lib/readJson' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-config/src/webpack.config.base' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-config/src/webpack.config.client.defaults' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-config/src/webpack.config.client.development' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-config/src/webpack.config.client.production' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-config/src/webpack.config' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-config/src/webpack.config.server.defaults' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-config/src/webpack.config.server.development' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-config/src/webpack.config.server.production' {
  declare module.exports: any;
}

// Filename aliases
declare module '@immowelt/my-fancy-ui-config/src/index.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-config/src/index'>;
}
declare module '@immowelt/my-fancy-ui-config/src/index.production.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-config/src/index.production'>;
}
declare module '@immowelt/my-fancy-ui-config/src/lib/readJson.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-config/src/lib/readJson'>;
}
declare module '@immowelt/my-fancy-ui-config/src/webpack.config.base.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-config/src/webpack.config.base'>;
}
declare module '@immowelt/my-fancy-ui-config/src/webpack.config.client.defaults.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-config/src/webpack.config.client.defaults'>;
}
declare module '@immowelt/my-fancy-ui-config/src/webpack.config.client.development.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-config/src/webpack.config.client.development'>;
}
declare module '@immowelt/my-fancy-ui-config/src/webpack.config.client.production.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-config/src/webpack.config.client.production'>;
}
declare module '@immowelt/my-fancy-ui-config/src/webpack.config.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-config/src/webpack.config'>;
}
declare module '@immowelt/my-fancy-ui-config/src/webpack.config.server.defaults.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-config/src/webpack.config.server.defaults'>;
}
declare module '@immowelt/my-fancy-ui-config/src/webpack.config.server.development.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-config/src/webpack.config.server.development'>;
}
declare module '@immowelt/my-fancy-ui-config/src/webpack.config.server.production.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-config/src/webpack.config.server.production'>;
}
