// flow-typed signature: 6e629d50225e5b8830ea97a43c67a0a0
// flow-typed version: <<STUB>>/@immowelt/eslint-config-immowelt-react_v2.0.2/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@immowelt/eslint-config-immowelt-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@immowelt/eslint-config-immowelt-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@immowelt/eslint-config-immowelt-react/src/index' {
  declare module.exports: any;
}

declare module '@immowelt/eslint-config-immowelt-react/src/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module '@immowelt/eslint-config-immowelt-react/src/index.js' {
  declare module.exports: $Exports<'@immowelt/eslint-config-immowelt-react/src/index'>;
}
declare module '@immowelt/eslint-config-immowelt-react/src/index.spec.js' {
  declare module.exports: $Exports<'@immowelt/eslint-config-immowelt-react/src/index.spec'>;
}
