// flow-typed signature: 82e6850bf22c64f4730fbe69ead4443d
// flow-typed version: <<STUB>>/hypernova-client_v1.1.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hypernova-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hypernova-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hypernova-client/examples/exampleServer' {
  declare module.exports: any;
}

declare module 'hypernova-client/lib/index' {
  declare module.exports: any;
}

declare module 'hypernova-client/plugins/devModePlugin' {
  declare module.exports: any;
}

declare module 'hypernova-client/src/index' {
  declare module.exports: any;
}

declare module 'hypernova-client/test/broken-server-test' {
  declare module.exports: any;
}

declare module 'hypernova-client/test/no-plugin-test' {
  declare module.exports: any;
}

declare module 'hypernova-client/test/plugin-getComponentProps-test' {
  declare module.exports: any;
}

declare module 'hypernova-client/test/plugin-onError-test' {
  declare module.exports: any;
}

declare module 'hypernova-client/test/plugin-onSuccess-test' {
  declare module.exports: any;
}

declare module 'hypernova-client/test/plugin-prepareRequest-test' {
  declare module.exports: any;
}

declare module 'hypernova-client/test/plugin-shouldSendRequest-test' {
  declare module.exports: any;
}

declare module 'hypernova-client/test/plugin-willSendRequest-test' {
  declare module.exports: any;
}

declare module 'hypernova-client/test/rendererProvider' {
  declare module.exports: any;
}

declare module 'hypernova-client/test/runAssertions' {
  declare module.exports: any;
}

declare module 'hypernova-client/test/runTest' {
  declare module.exports: any;
}

declare module 'hypernova-client/test/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hypernova-client/examples/exampleServer.js' {
  declare module.exports: $Exports<'hypernova-client/examples/exampleServer'>;
}
declare module 'hypernova-client/lib/index.js' {
  declare module.exports: $Exports<'hypernova-client/lib/index'>;
}
declare module 'hypernova-client/plugins/devModePlugin.js' {
  declare module.exports: $Exports<'hypernova-client/plugins/devModePlugin'>;
}
declare module 'hypernova-client/src/index.js' {
  declare module.exports: $Exports<'hypernova-client/src/index'>;
}
declare module 'hypernova-client/test/broken-server-test.js' {
  declare module.exports: $Exports<'hypernova-client/test/broken-server-test'>;
}
declare module 'hypernova-client/test/no-plugin-test.js' {
  declare module.exports: $Exports<'hypernova-client/test/no-plugin-test'>;
}
declare module 'hypernova-client/test/plugin-getComponentProps-test.js' {
  declare module.exports: $Exports<'hypernova-client/test/plugin-getComponentProps-test'>;
}
declare module 'hypernova-client/test/plugin-onError-test.js' {
  declare module.exports: $Exports<'hypernova-client/test/plugin-onError-test'>;
}
declare module 'hypernova-client/test/plugin-onSuccess-test.js' {
  declare module.exports: $Exports<'hypernova-client/test/plugin-onSuccess-test'>;
}
declare module 'hypernova-client/test/plugin-prepareRequest-test.js' {
  declare module.exports: $Exports<'hypernova-client/test/plugin-prepareRequest-test'>;
}
declare module 'hypernova-client/test/plugin-shouldSendRequest-test.js' {
  declare module.exports: $Exports<'hypernova-client/test/plugin-shouldSendRequest-test'>;
}
declare module 'hypernova-client/test/plugin-willSendRequest-test.js' {
  declare module.exports: $Exports<'hypernova-client/test/plugin-willSendRequest-test'>;
}
declare module 'hypernova-client/test/rendererProvider.js' {
  declare module.exports: $Exports<'hypernova-client/test/rendererProvider'>;
}
declare module 'hypernova-client/test/runAssertions.js' {
  declare module.exports: $Exports<'hypernova-client/test/runAssertions'>;
}
declare module 'hypernova-client/test/runTest.js' {
  declare module.exports: $Exports<'hypernova-client/test/runTest'>;
}
declare module 'hypernova-client/test/server.js' {
  declare module.exports: $Exports<'hypernova-client/test/server'>;
}
