// flow-typed signature: b47c01fd006abfea47b3943b44f2c9d9
// flow-typed version: <<STUB>>/webpack-livereload-plugin_v1.0.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-livereload-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-livereload-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-livereload-plugin/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-livereload-plugin/index' {
  declare module.exports: $Exports<'webpack-livereload-plugin'>;
}
declare module 'webpack-livereload-plugin/index.js' {
  declare module.exports: $Exports<'webpack-livereload-plugin'>;
}
declare module 'webpack-livereload-plugin/test.js' {
  declare module.exports: $Exports<'webpack-livereload-plugin/test'>;
}
