// flow-typed signature: 4b888ea8ff180c951223ac14be9c0955
// flow-typed version: <<STUB>>/@immowelt/babel-preset-immowelt-react_v1.2.2/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@immowelt/babel-preset-immowelt-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@immowelt/babel-preset-immowelt-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@immowelt/babel-preset-immowelt-react/src/createConfig' {
  declare module.exports: any;
}

declare module '@immowelt/babel-preset-immowelt-react/src/index' {
  declare module.exports: any;
}

declare module '@immowelt/babel-preset-immowelt-react/src/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module '@immowelt/babel-preset-immowelt-react/src/createConfig.js' {
  declare module.exports: $Exports<'@immowelt/babel-preset-immowelt-react/src/createConfig'>;
}
declare module '@immowelt/babel-preset-immowelt-react/src/index.js' {
  declare module.exports: $Exports<'@immowelt/babel-preset-immowelt-react/src/index'>;
}
declare module '@immowelt/babel-preset-immowelt-react/src/index.spec.js' {
  declare module.exports: $Exports<'@immowelt/babel-preset-immowelt-react/src/index.spec'>;
}
