// flow-typed signature: 9a2f87a8dd9f871fc28f2a10e7afeec0
// flow-typed version: <<STUB>>/@immowelt/jest-preset-react_v1.1.1/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@immowelt/jest-preset-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@immowelt/jest-preset-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@immowelt/jest-preset-react/src/setupFiles/enzyme' {
  declare module.exports: any;
}

declare module '@immowelt/jest-preset-react/src/transforms/css' {
  declare module.exports: any;
}

declare module '@immowelt/jest-preset-react/src/transforms/css.spec' {
  declare module.exports: any;
}

declare module '@immowelt/jest-preset-react/src/transforms/file' {
  declare module.exports: any;
}

declare module '@immowelt/jest-preset-react/src/transforms/file.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module '@immowelt/jest-preset-react/src/setupFiles/enzyme.js' {
  declare module.exports: $Exports<'@immowelt/jest-preset-react/src/setupFiles/enzyme'>;
}
declare module '@immowelt/jest-preset-react/src/transforms/css.js' {
  declare module.exports: $Exports<'@immowelt/jest-preset-react/src/transforms/css'>;
}
declare module '@immowelt/jest-preset-react/src/transforms/css.spec.js' {
  declare module.exports: $Exports<'@immowelt/jest-preset-react/src/transforms/css.spec'>;
}
declare module '@immowelt/jest-preset-react/src/transforms/file.js' {
  declare module.exports: $Exports<'@immowelt/jest-preset-react/src/transforms/file'>;
}
declare module '@immowelt/jest-preset-react/src/transforms/file.spec.js' {
  declare module.exports: $Exports<'@immowelt/jest-preset-react/src/transforms/file.spec'>;
}
