// flow-typed signature: 433236b36e2466a94ac42673458ebca3
// flow-typed version: <<STUB>>/@immowelt/my-fancy-ui-logger_v0.0.0-development/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@immowelt/my-fancy-ui-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@immowelt/my-fancy-ui-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@immowelt/my-fancy-ui-logger/flow-typed/npm/@immowelt/babel-preset-immowelt-node_vx.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-logger/flow-typed/npm/@immowelt/babel-preset-immowelt-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-logger/flow-typed/npm/@immowelt/eslint-config-immowelt-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-logger/flow-typed/npm/@immowelt/jest-preset-node_vx.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-logger/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-logger/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-logger/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-logger/flow-typed/npm/jest_v21.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-logger/src/index' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-logger/src/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module '@immowelt/my-fancy-ui-logger/flow-typed/npm/@immowelt/babel-preset-immowelt-node_vx.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-logger/flow-typed/npm/@immowelt/babel-preset-immowelt-node_vx.x.x'>;
}
declare module '@immowelt/my-fancy-ui-logger/flow-typed/npm/@immowelt/babel-preset-immowelt-react_vx.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-logger/flow-typed/npm/@immowelt/babel-preset-immowelt-react_vx.x.x'>;
}
declare module '@immowelt/my-fancy-ui-logger/flow-typed/npm/@immowelt/eslint-config-immowelt-react_vx.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-logger/flow-typed/npm/@immowelt/eslint-config-immowelt-react_vx.x.x'>;
}
declare module '@immowelt/my-fancy-ui-logger/flow-typed/npm/@immowelt/jest-preset-node_vx.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-logger/flow-typed/npm/@immowelt/jest-preset-node_vx.x.x'>;
}
declare module '@immowelt/my-fancy-ui-logger/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-logger/flow-typed/npm/eslint_vx.x.x'>;
}
declare module '@immowelt/my-fancy-ui-logger/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-logger/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@immowelt/my-fancy-ui-logger/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-logger/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module '@immowelt/my-fancy-ui-logger/flow-typed/npm/jest_v21.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-logger/flow-typed/npm/jest_v21.x.x'>;
}
declare module '@immowelt/my-fancy-ui-logger/src/index.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-logger/src/index'>;
}
declare module '@immowelt/my-fancy-ui-logger/src/index.spec.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-logger/src/index.spec'>;
}
