// flow-typed signature: 282b98a36509a992679084d3800da3c8
// flow-typed version: <<STUB>>/@immowelt/my-fancy-ui-components_v0.0.0-development/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@immowelt/my-fancy-ui-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@immowelt/my-fancy-ui-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/@immowelt/babel-preset-immowelt-node_vx.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/@immowelt/babel-preset-immowelt-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/@immowelt/eslint-config-immowelt-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/@immowelt/jest-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/classcat_vx.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/empty_vx.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/enzyme_v3.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/enzyme-adapter-react-16_vx.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/enzyme-to-json_vx.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/jest_v21.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/prop-types_v15.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/react-test-renderer_vx.x.x' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-components/src/Button/index' {
  declare module.exports: any;
}

declare module '@immowelt/my-fancy-ui-components/src/Button/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/@immowelt/babel-preset-immowelt-node_vx.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-components/flow-typed/npm/@immowelt/babel-preset-immowelt-node_vx.x.x'>;
}
declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/@immowelt/babel-preset-immowelt-react_vx.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-components/flow-typed/npm/@immowelt/babel-preset-immowelt-react_vx.x.x'>;
}
declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/@immowelt/eslint-config-immowelt-react_vx.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-components/flow-typed/npm/@immowelt/eslint-config-immowelt-react_vx.x.x'>;
}
declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/@immowelt/jest-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-components/flow-typed/npm/@immowelt/jest-preset-react_vx.x.x'>;
}
declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/classcat_vx.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-components/flow-typed/npm/classcat_vx.x.x'>;
}
declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/empty_vx.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-components/flow-typed/npm/empty_vx.x.x'>;
}
declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/enzyme_v3.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-components/flow-typed/npm/enzyme_v3.x.x'>;
}
declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/enzyme-adapter-react-16_vx.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-components/flow-typed/npm/enzyme-adapter-react-16_vx.x.x'>;
}
declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/enzyme-to-json_vx.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-components/flow-typed/npm/enzyme-to-json_vx.x.x'>;
}
declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-components/flow-typed/npm/eslint_vx.x.x'>;
}
declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-components/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-components/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/jest_v21.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-components/flow-typed/npm/jest_v21.x.x'>;
}
declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/prop-types_v15.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-components/flow-typed/npm/prop-types_v15.x.x'>;
}
declare module '@immowelt/my-fancy-ui-components/flow-typed/npm/react-test-renderer_vx.x.x.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-components/flow-typed/npm/react-test-renderer_vx.x.x'>;
}
declare module '@immowelt/my-fancy-ui-components/src/Button/index.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-components/src/Button/index'>;
}
declare module '@immowelt/my-fancy-ui-components/src/Button/index.spec.js' {
  declare module.exports: $Exports<'@immowelt/my-fancy-ui-components/src/Button/index.spec'>;
}
