// flow-typed signature: 897c17d63051a381609b682142b70a5c
// flow-typed version: <<STUB>>/invalidate-module_v1.0.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'invalidate-module'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'invalidate-module' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'invalidate-module/test/a' {
  declare module.exports: any;
}

declare module 'invalidate-module/test/b' {
  declare module.exports: any;
}

declare module 'invalidate-module/test/c' {
  declare module.exports: any;
}

declare module 'invalidate-module/test/d' {
  declare module.exports: any;
}

declare module 'invalidate-module/test/e' {
  declare module.exports: any;
}

declare module 'invalidate-module/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'invalidate-module/index' {
  declare module.exports: $Exports<'invalidate-module'>;
}
declare module 'invalidate-module/index.js' {
  declare module.exports: $Exports<'invalidate-module'>;
}
declare module 'invalidate-module/test/a.js' {
  declare module.exports: $Exports<'invalidate-module/test/a'>;
}
declare module 'invalidate-module/test/b.js' {
  declare module.exports: $Exports<'invalidate-module/test/b'>;
}
declare module 'invalidate-module/test/c.js' {
  declare module.exports: $Exports<'invalidate-module/test/c'>;
}
declare module 'invalidate-module/test/d.js' {
  declare module.exports: $Exports<'invalidate-module/test/d'>;
}
declare module 'invalidate-module/test/e.js' {
  declare module.exports: $Exports<'invalidate-module/test/e'>;
}
declare module 'invalidate-module/test/test.js' {
  declare module.exports: $Exports<'invalidate-module/test/test'>;
}
