// flow-typed signature: c37a4842443f624ef9d9881da3992d43
// flow-typed version: <<STUB>>/@inkdpixels/commit-analyzer_v^1.0.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@inkdpixels/commit-analyzer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@inkdpixels/commit-analyzer' {
  declare module.exports: any;
}
