// flow-typed signature: 86c1a84850a7a5639ca887e7d5be9078
// flow-typed version: <<STUB>>/@inkdpixels/release-notes-generator_v^1.0.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@inkdpixels/release-notes-generator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@inkdpixels/release-notes-generator' {
  declare module.exports: any;
}
